### ISSUE TITLE
Node Processes

### ISSUE THREAD

**Issue by danceasarxx** [Railk/T3S#75]
TS3 creates two node processes for tss when a  .ts file is loaded, what's more annoying is the fact that it doesn't close this processes when the view is closed. Read in the readme that I'm to setup the plugin in my .sublime-project file but nothing changed.(Not every one has 8GB ram and 2ghz processor)

**Comment by Phaiax** [comment]
see my last comment in https://github.com/Railk/T3S/pull/63 (tl;dr there is a new plugin named ArcticTypescript)

Arctic Typescript has changed this behaviour and only uses one process.

**Comment by danceasarxx** [comment]
Thanks a lot...will check it out now
