### ISSUE TITLE
Add a license for the repository

### ISSUE THREAD

**Issue by DanielRosenwasser** [Railk/T3S#84]
Seems like it would be valuable to this project as well as others if a license was adopted.

Apache 2.0 would probably be the most pragmatic license, as it is sufficiently permissive and is compatible with the TypeScript compiler itself.

If it's easier for you, I could send a PR to address this.

**Comment by kenrick95** [comment]
He added license per 0a8a6daedace66d651a4921c7c1f10919e02616c commit (MIT License)

**Comment by DanielRosenwasser** [comment]
Great! Thanks!
